---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-registry.fullname" . }}-secret
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
  {{- with .Values.cronjob.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc}}
{{- end }}

